apiVersion: v1
kind: Service          
metadata:
  name: veridid-dummy-app-service
  namespace: eks-sample-app
spec:
  type: LoadBalancer
  selector:
    app: veridid-dummy-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001